using System;
using System.Collections.Generic;
using System.Text;

namespace PII_Security
{
    /// <summary>
    /// NOTE: MUST have same namespace as the entities generated by entity framework
    ///       in order to extend that class to use these fields for decrypted values.
    /// </summary>
    public partial class Customer
    {
        [PII]
        public DateTime DateOfBirth => DateTime.Parse(PiiDateOfBirth.Decrypt());

        [PII]
        public string SocialInsuranceNumber => PiiSocialInsuranceNumber.Decrypt();

        [PII]
        public decimal AnnualSalary => decimal.Parse(PiiAnnualSalary.Decrypt());
    }

}
